/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAuthorizationLoginPostRequest
 */
export interface ApiAuthorizationLoginPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiAuthorizationLoginPostRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ApiAuthorizationLoginPostRequest
     */
    password: string;
}

/**
 * Check if a given object implements the ApiAuthorizationLoginPostRequest interface.
 */
export function instanceOfApiAuthorizationLoginPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function ApiAuthorizationLoginPostRequestFromJSON(json: any): ApiAuthorizationLoginPostRequest {
    return ApiAuthorizationLoginPostRequestFromJSONTyped(json, false);
}

export function ApiAuthorizationLoginPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAuthorizationLoginPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function ApiAuthorizationLoginPostRequestToJSON(value?: ApiAuthorizationLoginPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}

