/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiUserUpdatePutRequest
 */
export interface ApiUserUpdatePutRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiUserUpdatePutRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiUserUpdatePutRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiUserUpdatePutRequest
     */
    password?: string | null;
}

/**
 * Check if a given object implements the ApiUserUpdatePutRequest interface.
 */
export function instanceOfApiUserUpdatePutRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function ApiUserUpdatePutRequestFromJSON(json: any): ApiUserUpdatePutRequest {
    return ApiUserUpdatePutRequestFromJSONTyped(json, false);
}

export function ApiUserUpdatePutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUserUpdatePutRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function ApiUserUpdatePutRequestToJSON(value?: ApiUserUpdatePutRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'password': value.password,
    };
}

