/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentAddDTO
 */
export interface CommentAddDTO {
    /**
     * 
     * @type {string}
     * @memberof CommentAddDTO
     */
    commentText: string;
    /**
     * 
     * @type {string}
     * @memberof CommentAddDTO
     */
    authorId: string;
    /**
     * 
     * @type {string}
     * @memberof CommentAddDTO
     */
    postId: string;
}

/**
 * Check if a given object implements the CommentAddDTO interface.
 */
export function instanceOfCommentAddDTO(value: object): value is CommentAddDTO {
    if (!('commentText' in value) || value['commentText'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('postId' in value) || value['postId'] === undefined) return false;
    return true;
}

export function CommentAddDTOFromJSON(json: any): CommentAddDTO {
    return CommentAddDTOFromJSONTyped(json, false);
}

export function CommentAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'commentText': json['commentText'],
        'authorId': json['authorId'],
        'postId': json['postId'],
    };
}

export function CommentAddDTOToJSON(json: any): CommentAddDTO {
    return CommentAddDTOToJSONTyped(json, false);
}

export function CommentAddDTOToJSONTyped(value?: CommentAddDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commentText': value['commentText'],
        'authorId': value['authorId'],
        'postId': value['postId'],
    };
}

