/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentUpdateDTO
 */
export interface CommentUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof CommentUpdateDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CommentUpdateDTO
     */
    commentText: string;
}

/**
 * Check if a given object implements the CommentUpdateDTO interface.
 */
export function instanceOfCommentUpdateDTO(value: object): value is CommentUpdateDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('commentText' in value) || value['commentText'] === undefined) return false;
    return true;
}

export function CommentUpdateDTOFromJSON(json: any): CommentUpdateDTO {
    return CommentUpdateDTOFromJSONTyped(json, false);
}

export function CommentUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'commentText': json['commentText'],
    };
}

export function CommentUpdateDTOToJSON(json: any): CommentUpdateDTO {
    return CommentUpdateDTOToJSONTyped(json, false);
}

export function CommentUpdateDTOToJSONTyped(value?: CommentUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'commentText': value['commentText'],
    };
}

