/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommentDTO } from './CommentDTO';
import {
    CommentDTOFromJSON,
    CommentDTOFromJSONTyped,
    CommentDTOToJSON,
    CommentDTOToJSONTyped,
} from './CommentDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CommentDTORequestResponse
 */
export interface CommentDTORequestResponse {
    /**
     * 
     * @type {CommentDTO}
     * @memberof CommentDTORequestResponse
     */
    readonly response?: CommentDTO | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CommentDTORequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the CommentDTORequestResponse interface.
 */
export function instanceOfCommentDTORequestResponse(value: object): value is CommentDTORequestResponse {
    return true;
}

export function CommentDTORequestResponseFromJSON(json: any): CommentDTORequestResponse {
    return CommentDTORequestResponseFromJSONTyped(json, false);
}

export function CommentDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : CommentDTOFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CommentDTORequestResponseToJSON(json: any): CommentDTORequestResponse {
    return CommentDTORequestResponseToJSONTyped(json, false);
}

export function CommentDTORequestResponseToJSONTyped(value?: Omit<CommentDTORequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

