/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';
import type { CommentDTOPagedResponse } from './CommentDTOPagedResponse';
import {
    CommentDTOPagedResponseFromJSON,
    CommentDTOPagedResponseFromJSONTyped,
    CommentDTOPagedResponseToJSON,
    CommentDTOPagedResponseToJSONTyped,
} from './CommentDTOPagedResponse';

/**
 * 
 * @export
 * @interface CommentDTOPagedResponseRequestResponse
 */
export interface CommentDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {CommentDTOPagedResponse}
     * @memberof CommentDTOPagedResponseRequestResponse
     */
    readonly response?: CommentDTOPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CommentDTOPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the CommentDTOPagedResponseRequestResponse interface.
 */
export function instanceOfCommentDTOPagedResponseRequestResponse(value: object): value is CommentDTOPagedResponseRequestResponse {
    return true;
}

export function CommentDTOPagedResponseRequestResponseFromJSON(json: any): CommentDTOPagedResponseRequestResponse {
    return CommentDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function CommentDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : CommentDTOPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CommentDTOPagedResponseRequestResponseToJSON(json: any): CommentDTOPagedResponseRequestResponse {
    return CommentDTOPagedResponseRequestResponseToJSONTyped(json, false);
}

export function CommentDTOPagedResponseRequestResponseToJSONTyped(value?: Omit<CommentDTOPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

