/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentDTO
 */
export interface CommentDTO {
    /**
     * 
     * @type {string}
     * @memberof CommentDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDTO
     */
    commentText: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDTO
     */
    authorId: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDTO
     */
    postId: string;
}

/**
 * Check if a given object implements the CommentDTO interface.
 */
export function instanceOfCommentDTO(value: object): value is CommentDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('commentText' in value) || value['commentText'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('postId' in value) || value['postId'] === undefined) return false;
    return true;
}

export function CommentDTOFromJSON(json: any): CommentDTO {
    return CommentDTOFromJSONTyped(json, false);
}

export function CommentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'commentText': json['commentText'],
        'authorId': json['authorId'],
        'postId': json['postId'],
    };
}

export function CommentDTOToJSON(json: any): CommentDTO {
    return CommentDTOToJSONTyped(json, false);
}

export function CommentDTOToJSONTyped(value?: CommentDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'commentText': value['commentText'],
        'authorId': value['authorId'],
        'postId': value['postId'],
    };
}

