/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommentDTO } from './CommentDTO';
import {
    CommentDTOFromJSON,
    CommentDTOFromJSONTyped,
    CommentDTOToJSON,
    CommentDTOToJSONTyped,
} from './CommentDTO';

/**
 * 
 * @export
 * @interface CommentDTOPagedResponse
 */
export interface CommentDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof CommentDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof CommentDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof CommentDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<CommentDTO>}
     * @memberof CommentDTOPagedResponse
     */
    data: Array<CommentDTO>;
}

/**
 * Check if a given object implements the CommentDTOPagedResponse interface.
 */
export function instanceOfCommentDTOPagedResponse(value: object): value is CommentDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CommentDTOPagedResponseFromJSON(json: any): CommentDTOPagedResponse {
    return CommentDTOPagedResponseFromJSONTyped(json, false);
}

export function CommentDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(CommentDTOFromJSON)),
    };
}

export function CommentDTOPagedResponseToJSON(json: any): CommentDTOPagedResponse {
    return CommentDTOPagedResponseToJSONTyped(json, false);
}

export function CommentDTOPagedResponseToJSONTyped(value?: CommentDTOPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(CommentDTOToJSON)),
    };
}

