/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IngredientDTOPagedResponse } from './IngredientDTOPagedResponse';
import {
    IngredientDTOPagedResponseFromJSON,
    IngredientDTOPagedResponseFromJSONTyped,
    IngredientDTOPagedResponseToJSON,
    IngredientDTOPagedResponseToJSONTyped,
} from './IngredientDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 *
 * @export
 * @interface IngredientDTOPagedResponseRequestResponse
 */
export interface IngredientDTOPagedResponseRequestResponse {
    /**
     *
     * @type {IngredientDTOPagedResponse}
     * @memberof IngredientDTOPagedResponseRequestResponse
     */
    readonly response?: IngredientDTOPagedResponse | null;
    /**
     *
     * @type {ErrorMessage}
     * @memberof IngredientDTOPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the IngredientDTOPagedResponseRequestResponse interface.
 */
export function instanceOfIngredientDTOPagedResponseRequestResponse(value: object): value is IngredientDTOPagedResponseRequestResponse {
    return true;
}

export function IngredientDTOPagedResponseRequestResponseFromJSON(json: any): IngredientDTOPagedResponseRequestResponse {
    return IngredientDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function IngredientDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {

        'response': json['response'] == null ? undefined : IngredientDTOPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function IngredientDTOPagedResponseRequestResponseToJSON(json: any): IngredientDTOPagedResponseRequestResponse {
    return IngredientDTOPagedResponseRequestResponseToJSONTyped(json, false);
}

export function IngredientDTOPagedResponseRequestResponseToJSONTyped(value?: Omit<IngredientDTOPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

    };
}

