/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IngredientDTO } from './IngredientDTO';
import {
    IngredientDTOFromJSON,
    IngredientDTOFromJSONTyped,
    IngredientDTOToJSON,
    IngredientDTOToJSONTyped,
} from './IngredientDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface IngredientDTORequestResponse
 */
export interface IngredientDTORequestResponse {
    /**
     * 
     * @type {IngredientDTO}
     * @memberof IngredientDTORequestResponse
     */
    readonly response?: IngredientDTO | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof IngredientDTORequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the IngredientDTORequestResponse interface.
 */
export function instanceOfIngredientDTORequestResponse(value: object): value is IngredientDTORequestResponse {
    return true;
}

export function IngredientDTORequestResponseFromJSON(json: any): IngredientDTORequestResponse {
    return IngredientDTORequestResponseFromJSONTyped(json, false);
}

export function IngredientDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : IngredientDTOFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function IngredientDTORequestResponseToJSON(json: any): IngredientDTORequestResponse {
    return IngredientDTORequestResponseToJSONTyped(json, false);
}

export function IngredientDTORequestResponseToJSONTyped(value?: Omit<IngredientDTORequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

