/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IngredientDTO } from './IngredientDTO';
import {
    IngredientDTOFromJSON,
    IngredientDTOFromJSONTyped,
    IngredientDTOToJSON,
    IngredientDTOToJSONTyped,
} from './IngredientDTO';

/**
 * 
 * @export
 * @interface IngredientDTOPagedResponse
 */
export interface IngredientDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof IngredientDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof IngredientDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof IngredientDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<IngredientDTO>}
     * @memberof IngredientDTOPagedResponse
     */
    data: Array<IngredientDTO>;
}

/**
 * Check if a given object implements the IngredientDTOPagedResponse interface.
 */
export function instanceOfIngredientDTOPagedResponse(value: object): value is IngredientDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function IngredientDTOPagedResponseFromJSON(json: any): IngredientDTOPagedResponse {
    return IngredientDTOPagedResponseFromJSONTyped(json, false);
}

export function IngredientDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(IngredientDTOFromJSON)),
    };
}

export function IngredientDTOPagedResponseToJSON(json: any): IngredientDTOPagedResponse {
    return IngredientDTOPagedResponseToJSONTyped(json, false);
}

export function IngredientDTOPagedResponseToJSONTyped(value?: IngredientDTOPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(IngredientDTOToJSON)),
    };
}

