/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngredientUpdateDTO
 */
export interface IngredientUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof IngredientUpdateDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof IngredientUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IngredientUpdateDTO
     */
    description?: string | null;
}

/**
 * Check if a given object implements the IngredientUpdateDTO interface.
 */
export function instanceOfIngredientUpdateDTO(value: object): value is IngredientUpdateDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function IngredientUpdateDTOFromJSON(json: any): IngredientUpdateDTO {
    return IngredientUpdateDTOFromJSONTyped(json, false);
}

export function IngredientUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function IngredientUpdateDTOToJSON(json: any): IngredientUpdateDTO {
    return IngredientUpdateDTOToJSONTyped(json, false);
}

export function IngredientUpdateDTOToJSONTyped(value?: IngredientUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
    };
}

