/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Ingredient
 */
export interface Ingredient {
    /**
     * 
     * @type {string}
     * @memberof Ingredient
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof Ingredient
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Ingredient
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Ingredient
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Ingredient
     */
    description: string;
}

/**
 * Check if a given object implements the Ingredient interface.
 */
export function instanceOfIngredient(value: object): value is Ingredient {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function IngredientFromJSON(json: any): Ingredient {
    return IngredientFromJSONTyped(json, false);
}

export function IngredientFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ingredient {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'name': json['name'],
        'description': json['description'],
    };
}

export function IngredientToJSON(json: any): Ingredient {
    return IngredientToJSONTyped(json, false);
}

export function IngredientToJSONTyped(value?: Ingredient | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'name': value['name'],
        'description': value['description'],
    };
}

