/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngredientDTO
 */
export interface IngredientDTO {
    /**
     * 
     * @type {string}
     * @memberof IngredientDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof IngredientDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IngredientDTO
     */
    description: string;
}

/**
 * Check if a given object implements the IngredientDTO interface.
 */
export function instanceOfIngredientDTO(value: object): value is IngredientDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function IngredientDTOFromJSON(json: any): IngredientDTO {
    return IngredientDTOFromJSONTyped(json, false);
}

export function IngredientDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function IngredientDTOToJSON(json: any): IngredientDTO {
    return IngredientDTOToJSONTyped(json, false);
}

export function IngredientDTOToJSONTyped(value?: IngredientDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
    };
}

