/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostDTO } from './PostDTO';
import {
    PostDTOFromJSON,
    PostDTOFromJSONTyped,
    PostDTOToJSON,
    PostDTOToJSONTyped,
} from './PostDTO';

/**
 * 
 * @export
 * @interface PostDTOPagedResponse
 */
export interface PostDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof PostDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PostDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PostDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<PostDTO>}
     * @memberof PostDTOPagedResponse
     */
    data: Array<PostDTO>;
}

/**
 * Check if a given object implements the PostDTOPagedResponse interface.
 */
export function instanceOfPostDTOPagedResponse(value: object): value is PostDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PostDTOPagedResponseFromJSON(json: any): PostDTOPagedResponse {
    return PostDTOPagedResponseFromJSONTyped(json, false);
}

export function PostDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(PostDTOFromJSON)),
    };
}

export function PostDTOPagedResponseToJSON(json: any): PostDTOPagedResponse {
    return PostDTOPagedResponseToJSONTyped(json, false);
}

export function PostDTOPagedResponseToJSONTyped(value?: PostDTOPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(PostDTOToJSON)),
    };
}

