/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAddDTO
 */
export interface PostAddDTO {
    /**
     * 
     * @type {string}
     * @memberof PostAddDTO
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof PostAddDTO
     */
    authorId: string;
    /**
     * 
     * @type {string}
     * @memberof PostAddDTO
     */
    recipeId: string;
}

/**
 * Check if a given object implements the PostAddDTO interface.
 */
export function instanceOfPostAddDTO(value: object): value is PostAddDTO {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('recipeId' in value) || value['recipeId'] === undefined) return false;
    return true;
}

export function PostAddDTOFromJSON(json: any): PostAddDTO {
    return PostAddDTOFromJSONTyped(json, false);
}

export function PostAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'authorId': json['authorId'],
        'recipeId': json['recipeId'],
    };
}

export function PostAddDTOToJSON(json: any): PostAddDTO {
    return PostAddDTOToJSONTyped(json, false);
}

export function PostAddDTOToJSONTyped(value?: PostAddDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'authorId': value['authorId'],
        'recipeId': value['recipeId'],
    };
}

