/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostDTOPagedResponse } from './PostDTOPagedResponse';
import {
    PostDTOPagedResponseFromJSON,
    PostDTOPagedResponseFromJSONTyped,
    PostDTOPagedResponseToJSON,
    PostDTOPagedResponseToJSONTyped,
} from './PostDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface PostDTOPagedResponseRequestResponse
 */
export interface PostDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {PostDTOPagedResponse}
     * @memberof PostDTOPagedResponseRequestResponse
     */
    readonly response?: PostDTOPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof PostDTOPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the PostDTOPagedResponseRequestResponse interface.
 */
export function instanceOfPostDTOPagedResponseRequestResponse(value: object): value is PostDTOPagedResponseRequestResponse {
    return true;
}

export function PostDTOPagedResponseRequestResponseFromJSON(json: any): PostDTOPagedResponseRequestResponse {
    return PostDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function PostDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : PostDTOPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function PostDTOPagedResponseRequestResponseToJSON(json: any): PostDTOPagedResponseRequestResponse {
    return PostDTOPagedResponseRequestResponseToJSONTyped(json, false);
}

export function PostDTOPagedResponseRequestResponseToJSONTyped(value?: Omit<PostDTOPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

