/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeDTO } from './RecipeDTO';
import {
    RecipeDTOFromJSON,
    RecipeDTOFromJSONTyped,
    RecipeDTOToJSON,
    RecipeDTOToJSONTyped,
} from './RecipeDTO';

/**
 * 
 * @export
 * @interface RecipeDTOPagedResponse
 */
export interface RecipeDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof RecipeDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof RecipeDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof RecipeDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<RecipeDTO>}
     * @memberof RecipeDTOPagedResponse
     */
    data: Array<RecipeDTO>;
}

/**
 * Check if a given object implements the RecipeDTOPagedResponse interface.
 */
export function instanceOfRecipeDTOPagedResponse(value: object): value is RecipeDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RecipeDTOPagedResponseFromJSON(json: any): RecipeDTOPagedResponse {
    return RecipeDTOPagedResponseFromJSONTyped(json, false);
}

export function RecipeDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(RecipeDTOFromJSON)),
    };
}

export function RecipeDTOPagedResponseToJSON(json: any): RecipeDTOPagedResponse {
    return RecipeDTOPagedResponseToJSONTyped(json, false);
}

export function RecipeDTOPagedResponseToJSONTyped(value?: RecipeDTOPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(RecipeDTOToJSON)),
    };
}

