/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecipeUpdateDTO
 */
export interface RecipeUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof RecipeUpdateDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeUpdateDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeUpdateDTO
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeUpdateDTO
     */
    ingredientIds: Array<string>;
}

/**
 * Check if a given object implements the RecipeUpdateDTO interface.
 */
export function instanceOfRecipeUpdateDTO(value: object): value is RecipeUpdateDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('ingredientIds' in value) || value['ingredientIds'] === undefined) return false;
    return true;
}

export function RecipeUpdateDTOFromJSON(json: any): RecipeUpdateDTO {
    return RecipeUpdateDTOFromJSONTyped(json, false);
}

export function RecipeUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'ingredientIds': json['ingredientIds'],
    };
}

export function RecipeUpdateDTOToJSON(json: any): RecipeUpdateDTO {
    return RecipeUpdateDTOToJSONTyped(json, false);
}

export function RecipeUpdateDTOToJSONTyped(value?: RecipeUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'ingredientIds': value['ingredientIds'],
    };
}

