/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeDTO } from './RecipeDTO';
import {
    RecipeDTOFromJSON,
    RecipeDTOFromJSONTyped,
    RecipeDTOToJSON,
    RecipeDTOToJSONTyped,
} from './RecipeDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface RecipeDTORequestResponse
 */
export interface RecipeDTORequestResponse {
    /**
     * 
     * @type {RecipeDTO}
     * @memberof RecipeDTORequestResponse
     */
    readonly response?: RecipeDTO | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RecipeDTORequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RecipeDTORequestResponse interface.
 */
export function instanceOfRecipeDTORequestResponse(value: object): value is RecipeDTORequestResponse {
    return true;
}

export function RecipeDTORequestResponseFromJSON(json: any): RecipeDTORequestResponse {
    return RecipeDTORequestResponseFromJSONTyped(json, false);
}

export function RecipeDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : RecipeDTOFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RecipeDTORequestResponseToJSON(json: any): RecipeDTORequestResponse {
    return RecipeDTORequestResponseToJSONTyped(json, false);
}

export function RecipeDTORequestResponseToJSONTyped(value?: Omit<RecipeDTORequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

