/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';
import type { RecipeDTOPagedResponse } from './RecipeDTOPagedResponse';
import {
    RecipeDTOPagedResponseFromJSON,
    RecipeDTOPagedResponseFromJSONTyped,
    RecipeDTOPagedResponseToJSON,
    RecipeDTOPagedResponseToJSONTyped,
} from './RecipeDTOPagedResponse';

/**
 * 
 * @export
 * @interface RecipeDTOPagedResponseRequestResponse
 */
export interface RecipeDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {RecipeDTOPagedResponse}
     * @memberof RecipeDTOPagedResponseRequestResponse
     */
    readonly response?: RecipeDTOPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RecipeDTOPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RecipeDTOPagedResponseRequestResponse interface.
 */
export function instanceOfRecipeDTOPagedResponseRequestResponse(value: object): value is RecipeDTOPagedResponseRequestResponse {
    return true;
}

export function RecipeDTOPagedResponseRequestResponseFromJSON(json: any): RecipeDTOPagedResponseRequestResponse {
    return RecipeDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function RecipeDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : RecipeDTOPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RecipeDTOPagedResponseRequestResponseToJSON(json: any): RecipeDTOPagedResponseRequestResponse {
    return RecipeDTOPagedResponseRequestResponseToJSONTyped(json, false);
}

export function RecipeDTOPagedResponseRequestResponseToJSONTyped(value?: Omit<RecipeDTOPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

