/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecipeAddDTO
 */
export interface RecipeAddDTO {
    /**
     * 
     * @type {string}
     * @memberof RecipeAddDTO
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeAddDTO
     */
    ingredientIds: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RecipeAddDTO
     */
    authorId: string;
}

/**
 * Check if a given object implements the RecipeAddDTO interface.
 */
export function instanceOfRecipeAddDTO(value: object): value is RecipeAddDTO {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('ingredientIds' in value) || value['ingredientIds'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    return true;
}

export function RecipeAddDTOFromJSON(json: any): RecipeAddDTO {
    return RecipeAddDTOFromJSONTyped(json, false);
}

export function RecipeAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'ingredientIds': json['ingredientIds'],
        'authorId': json['authorId'],
    };
}

export function RecipeAddDTOToJSON(json: any): RecipeAddDTO {
    return RecipeAddDTOToJSONTyped(json, false);
}

export function RecipeAddDTOToJSONTyped(value?: RecipeAddDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'ingredientIds': value['ingredientIds'],
        'authorId': value['authorId'],
    };
}

