/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserFileDTOPagedResponse } from './UserFileDTOPagedResponse';
import {
    UserFileDTOPagedResponseFromJSON,
    UserFileDTOPagedResponseFromJSONTyped,
    UserFileDTOPagedResponseToJSON,
    UserFileDTOPagedResponseToJSONTyped,
} from './UserFileDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface UserFileDTOPagedResponseRequestResponse
 */
export interface UserFileDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {UserFileDTOPagedResponse}
     * @memberof UserFileDTOPagedResponseRequestResponse
     */
    readonly response?: UserFileDTOPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof UserFileDTOPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the UserFileDTOPagedResponseRequestResponse interface.
 */
export function instanceOfUserFileDTOPagedResponseRequestResponse(value: object): value is UserFileDTOPagedResponseRequestResponse {
    return true;
}

export function UserFileDTOPagedResponseRequestResponseFromJSON(json: any): UserFileDTOPagedResponseRequestResponse {
    return UserFileDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function UserFileDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFileDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : UserFileDTOPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function UserFileDTOPagedResponseRequestResponseToJSON(json: any): UserFileDTOPagedResponseRequestResponse {
    return UserFileDTOPagedResponseRequestResponseToJSONTyped(json, false);
}

export function UserFileDTOPagedResponseRequestResponseToJSONTyped(value?: Omit<UserFileDTOPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

