/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
    UserDTOToJSONTyped,
} from './UserDTO';

/**
 * 
 * @export
 * @interface UserFileDTO
 */
export interface UserFileDTO {
    /**
     * 
     * @type {string}
     * @memberof UserFileDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserFileDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserFileDTO
     */
    description?: string | null;
    /**
     * 
     * @type {UserDTO}
     * @memberof UserFileDTO
     */
    user: UserDTO;
    /**
     * 
     * @type {Date}
     * @memberof UserFileDTO
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserFileDTO
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the UserFileDTO interface.
 */
export function instanceOfUserFileDTO(value: object): value is UserFileDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UserFileDTOFromJSON(json: any): UserFileDTO {
    return UserFileDTOFromJSONTyped(json, false);
}

export function UserFileDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFileDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'user': UserDTOFromJSON(json['user']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function UserFileDTOToJSON(json: any): UserFileDTO {
    return UserFileDTOToJSONTyped(json, false);
}

export function UserFileDTOToJSONTyped(value?: UserFileDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'user': UserDTOToJSON(value['user']),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

