/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  IngredientAddDTO,
  IngredientDTOPagedResponseRequestResponse,
  IngredientDTORequestResponse,
  IngredientUpdateDTO,
  RequestResponse,
} from '../models/index';
import {
    IngredientAddDTOFromJSON,
    IngredientAddDTOToJSON,
    IngredientDTOPagedResponseRequestResponseFromJSON,
    IngredientDTOPagedResponseRequestResponseToJSON,
    IngredientDTORequestResponseFromJSON,
    IngredientDTORequestResponseToJSON,
    IngredientUpdateDTOFromJSON,
    IngredientUpdateDTOToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models/index';

export interface ApiIngredientAddPostRequest {
    ingredientAddDTO?: IngredientAddDTO;
}

export interface ApiIngredientDeleteIdDeleteRequest {
    id: string;
}

export interface ApiIngredientGetByIdIdGetRequest {
    id: string;
}

export interface ApiIngredientGetPageGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiIngredientUpdatePutRequest {
    ingredientUpdateDTO?: IngredientUpdateDTO;
}

/**
 *
 */
export class IngredientApi extends runtime.BaseAPI {

    /**
     */
    async apiIngredientAddPostRaw(requestParameters: ApiIngredientAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Ingredient/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IngredientAddDTOToJSON(requestParameters['ingredientAddDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiIngredientAddPost(requestParameters: ApiIngredientAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiIngredientAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiIngredientDeleteIdDeleteRaw(requestParameters: ApiIngredientDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiIngredientDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Ingredient/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiIngredientDeleteIdDelete(requestParameters: ApiIngredientDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiIngredientDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiIngredientGetByIdIdGetRaw(requestParameters: ApiIngredientGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IngredientDTORequestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiIngredientGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Ingredient/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IngredientDTORequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiIngredientGetByIdIdGet(requestParameters: ApiIngredientGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IngredientDTORequestResponse> {
        const response = await this.apiIngredientGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiIngredientGetPageGetRaw(requestParameters: ApiIngredientGetPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IngredientDTOPagedResponseRequestResponse>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['Search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Ingredient/GetPage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IngredientDTOPagedResponseRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiIngredientGetPageGet(requestParameters: ApiIngredientGetPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IngredientDTOPagedResponseRequestResponse> {
        const response = await this.apiIngredientGetPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiIngredientUpdatePutRaw(requestParameters: ApiIngredientUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Ingredient/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: IngredientUpdateDTOToJSON(requestParameters['ingredientUpdateDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiIngredientUpdatePut(requestParameters: ApiIngredientUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiIngredientUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
