/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PostAddDTO,
  PostDTOPagedResponseRequestResponse,
  PostDTORequestResponse,
  PostUpdateDTO,
  RequestResponse,
} from '../models/index';
import {
    PostAddDTOFromJSON,
    PostAddDTOToJSON,
    PostDTOPagedResponseRequestResponseFromJSON,
    PostDTOPagedResponseRequestResponseToJSON,
    PostDTORequestResponseFromJSON,
    PostDTORequestResponseToJSON,
    PostUpdateDTOFromJSON,
    PostUpdateDTOToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models/index';

export interface ApiPostAddPostRequest {
    postAddDTO?: PostAddDTO;
}

export interface ApiPostDeleteIdDeleteRequest {
    id: string;
}

export interface ApiPostGetByIdIdGetRequest {
    id: string;
}

export interface ApiPostGetPageByIdGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
    authorId?: string;
}

export interface ApiPostGetPageGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiPostUpdatePutRequest {
    postUpdateDTO?: PostUpdateDTO;
}

/**
 * 
 */
export class PostApi extends runtime.BaseAPI {

    /**
     */
    async apiPostAddPostRaw(requestParameters: ApiPostAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Post/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostAddDTOToJSON(requestParameters['postAddDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPostAddPost(requestParameters: ApiPostAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiPostAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPostDeleteIdDeleteRaw(requestParameters: ApiPostDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPostDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Post/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPostDeleteIdDelete(requestParameters: ApiPostDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiPostDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPostGetByIdIdGetRaw(requestParameters: ApiPostGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostDTORequestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPostGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Post/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostDTORequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPostGetByIdIdGet(requestParameters: ApiPostGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostDTORequestResponse> {
        const response = await this.apiPostGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPostGetPageByIdGetRaw(requestParameters: ApiPostGetPageByIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostDTOPagedResponseRequestResponse>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['Search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['authorId'] != null) {
            queryParameters['AuthorId'] = requestParameters['authorId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Post/GetPageById`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostDTOPagedResponseRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPostGetPageByIdGet(requestParameters: ApiPostGetPageByIdGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostDTOPagedResponseRequestResponse> {
        const response = await this.apiPostGetPageByIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPostGetPageGetRaw(requestParameters: ApiPostGetPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostDTOPagedResponseRequestResponse>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['Search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Post/GetPage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostDTOPagedResponseRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPostGetPageGet(requestParameters: ApiPostGetPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostDTOPagedResponseRequestResponse> {
        const response = await this.apiPostGetPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPostUpdatePutRaw(requestParameters: ApiPostUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Post/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PostUpdateDTOToJSON(requestParameters['postUpdateDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPostUpdatePut(requestParameters: ApiPostUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiPostUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
